### PR TITLE
Suggestion to add an article

### PR DESCRIPTION
**Pull request by enguerran**
## PR Checklist

>**Warning**
>PR not related to any issue

- [ ] Addresses an existing open issue: fixes #000
- [ ] That issue was marked as [accepting prs](https://github.com/LearningTypeScript/site/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [ ] Steps in [CONTRIBUTING.md](https://github.com/LearningTypeScript/site/blob/main/.github/CONTRIBUTING.md) were taken

## Overview

When I read [Richard Towers' article](https://www.richard-towers.com/2023/03/11/typescripting-the-technical-interview.html), I thought he could integrate the selection on this page.

This is a proposal, feel free to close the Pull Request if it is not convincing. For the record, I have not yet contacted Richard Towers to propose it.

### CODE REVIEW

**Review by JoshuaKGoldberg — APPROVED** [review]
Ha indeed, that article is great. Thanks for the suggestion @enguerran!

**Comment by JoshuaKGoldberg** [comment]
cc @richardTowers 🙂

**Comment by JoshuaKGoldberg** [comment]
We're live! https://www.learningtypescript.com/articles/extreme-explorations-of-typescripts-type-system#n-queens ✨

**Comment by enguerran** [comment]
Thanks to @oskarols  who shared the article with me!

**Comment by richardTowers** [comment]
Thanks for this folks!

**Pull request merged**
